# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime

ARG HTTP_PORT=80
ARG APP_HOME=/var/app

WORKDIR ${APP_HOME}
COPY ["/src/Docker.TesterWebsite/bin/Release/netcoreapp3.1/publish/win-x64/.", "./"]

ENV HOME ${APP_HOME}
ENV NAME dockertesterweb

# Make ports available to the world outside this container for main web interface
EXPOSE ${HTTP_PORT}

VOLUME /var/appdata

ENTRYPOINT ["dotnet", "Docker.TesterWebSite.dll"]